[package]
name = "blueshift_pinocchio_quantum_vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = "0.9.1"
pinocchio-system = "0.3.0"
solana-nostd-sha256 = "0.1.3"
solana-winternitz = "0.1.1"
